tryed to add first part of logic
pragmaticindustries/pql-demo pull request #3
Opened 2022-04-05 13:48 UTC by pragmayticer

running

Some comments

tryed to fix timestamp issue didnt work but have running state now and other stuff is working

fixed timestamp issue
implemented that even the last item will be saved with the right timestamps.

added tests

2022-04-06 10:08 UTC, JulianFeinauer commented on extract.py
> +    i: int = 0
Kannst du das noch so umbauen, dass wir das i nicht mehr brauchen?
Weil dann geht es ja auch auf einem (unendlichen) stream, quasi.
Weisst wie ich meine?
Es würde ja aber auch reichen, wenn du einfach ein "flag" hättest "letztes element" oder eben "nicht letztes element", oder?

2022-04-06 14:18 UTC, pragmayticer commented on extract.py
> +    i: int = 0
Ja

2022-04-06 15:29 UTC, JulianFeinauer requested changes

2022-04-06 15:29 UTC, JulianFeinauer commented on extract.py
> +        def __init__(self, config,element) -> None:
hier soll kein element rein. Der soll die states nur über die process state methode bekommen.

2022-04-06 15:29 UTC, JulianFeinauer commented on extract.py
> +            self.__init_context__(element)
Das hier muss beim ersten aufruf der "process_state" methode passieren

2022-04-06 15:29 UTC, JulianFeinauer commented on extract.py
> +    # assert end_result["Cycle"][1] == {'id': 2, 'start': 2, 'end': 6}
die könnten wir ja wieder aktivieren, oder?

2022-04-07 09:47 UTC, pragmayticer commented on extract.py
> +            self.__init_context__(element)
Ja

2022-04-07 09:51 UTC, pragmayticer commented on extract.py
> +    # assert end_result["Cycle"][1] == {'id': 2, 'start': 2, 'end': 6}
Normal schon Ja

2022-04-07 09:57 UTC, pragmayticer commented on extract.py
> +        def __init__(self, config,element) -> None:
ist glaub ich jetzt nicht mehr aktuell oder ???

2022-04-11 14:06 UTC, closed without merging